### PR TITLE
Added more tests and gh-actions

### PR DESCRIPTION
**Pull request by coderrsid**
Added tests for empty input and more unique crumbled csv patterns to test boundary cases and gh-actions configured for testing the files realtime .

### CODE REVIEW

**Review by tessus — COMMENTED** [review]
None of these tests have an empty line in the input. Also, it would be nice to haave proper naming for the tests.

**Comment by tessus** [comment]
The text `check if default export returns expected output` does not tell me anything.

Tests usually verify an edge case or something out of the ordinary. The naming should reflect that.
So every test is there for a reason. And that reason should be in the description.

**Comment by tessus** [comment]
what about the tests I suggested in my comment in the last PR. Once again, it seems you are not listening.

Here again for reference. However, these are just a few edge cases. Maybe there are more. All your tests are "normal" csv files. You need to find ways to break your code.

```
bla,this is very "very" strange,another bla
"very strange "hello" bla", c2, c3
c1,c2,another test \"now\" what
c1,c2,"another test \"now\" what"
```

**Comment by coderrsid** [comment]
> None of these tests have an empty line in the input. 
> what about the tests I suggested in my comment in the last PR. Once again, it seems you are not listening.

If by empty line you mean input like : `, , ,`
Then the test i added here: https://github.com/joplin/plugin-paste-special/pull/3/files#diff-b089a8d27e875c79af0c4db3ea4f5513748e4d29e02de6fcaba0ccad7b7043b9R3
produces output of a single header cell similarly empty line case as soon as it scans delimiter (in this case `, , ,`). Similarly it will produce 4 header cells as :
```
|  |   |   |  | 
| --- | --- | --- | --- |
```
Although, i've added the boundary case, this seems to be covered. But i'll add the test as you suggested ASAP.

> Also, it would be nice to have proper naming for the tests.
> The text check if default export returns expected output does not tell me anything.
> Tests usually verify an edge case or something out of the ordinary. The naming should reflect that.
> So every test is there for a reason. And that reason should be in the description.

Sure. That is the next thing planned as soon as we agree we've covered enough test cases.

**Comment by coderrsid** [comment]
> Here again for reference. However, these are just a few edge cases. Maybe there are more. All your tests are "normal" csv files. You need to find ways to break your code.
> 
> ```
> bla,this is very "very" strange,another bla
> "very strange "hello" bla", c2, c3
> c1,c2,another test \"now\" what
> c1,c2,"another test \"now\" what"
> ```

Absolutely, agreed. But i have always been looking for references like https://github.com/donatj/CsvToMarkdownTable/blob/master/test/test.js

A quick question i had in my mind. Should '\t'

**Comment by coderrsid** [comment]
> Here again for reference. However, these are just a few edge cases. Maybe there are more. All your tests are "normal" csv files. You need to find ways to break your code.

Absolutely, agreed. But i have always been looking for references like https://github.com/donatj/CsvToMarkdownTable/blob/master/test/test.js

> > ```
> > bla,this is very "very" strange,another bla
> > "very strange "hello" bla", c2, c3
> > c1,c2,another test \"now\" what
> > c1,c2,"another test \"now\" what"
> > ```

 A quick question: did you write this input in here or editor yourself or copied from the exported file after input into a csv editor (i.e. Microsoft Excel, etc.)?
 
 If you wrote it yourself here, the output is correct as expected which is
 
Parsed CSV Array (papaparse package): 
```
[["bla", "this is very "very" strange", "another bla"], ["very strange "hello" bla", " c2", " c3"], ["c1", "c2", "another test "now" what"], ["c1", "c2", "another test "now" what"]] 
```
Delimiter: `,`
Newline: `\n`

MD Output: 

 | bla | this is very "very" strange | another bla | 
| --- | --- | --- | 
| very strange "hello" bla |  c2 |  c3 | 
| c1 | c2 | another test "now" what | 
| c1 | c2 | another test "now" what |

**Comment by coderrsid** [comment]
One more query i had: should we add `\t` in `delimitersToGuess` attribute of papaparse config object ?
 @tessus @laurent

**Comment by tessus** [comment]
> But i have always been looking for references

The test cases are for testing your code, not somebody else's. Thus other test cases are only partly useful. Have you ever learned about test driven development? Usually you write test cases BEFORE you do the coding.
You think of all the possible edge cases and write positive and negative test cases. 

You just took a few test cases from a different project AFTER you wrote the code. Neither of which is proper testing.

> did you write this input in here or editor yourself 

Yes, I wrote it in the gh editor.

But as I said before, there might be other ones that need special attention. Every line of the tests I wrote addresses a certain edge case. Now you have to name the tests properly. And find other ones. Your test cases are mostly the same - only 3 really test anything out of the ordinary.

> One more query i had: should we add \t in delimitersToGuess attribute of papaparse config object ?

you tell us. And why.

**Comment by tessus** [comment]
> If by empty line you mean input like

You do know what an empty line is, right? No, I don't mean `, , ,`. This is not an empty line.

**Comment by coderrsid** [comment]
> The test cases are for testing your code,

Yes, i figured out test cases before only and i'm aware of test-driven development. I'm just trying to cover more cases here. I've been testing continuously through the integration. Trying to get input from community and you mentors about how should it will break.

**Comment by coderrsid** [comment]
> > If by empty line you mean input like
> 
> You do know what an empty line is, right? No, I don't mean `, , ,`. This is not an empty line.

No, i still don't understand what you mean by empty single line csv input. You can tell me if either it's one of below or you can comment here in code quotes: 
1. ` `   : test for this ( https://github.com/joplin/plugin-paste-special/pull/3/files#diff-b089a8d27e875c79af0c4db3ea4f5513748e4d29e02de6fcaba0ccad7b7043b9R3)
2. `,`
3.  `, , ,`

**Review by PackElend — COMMENTED** [review]
could you add additional comments what each test is for 
> 'check if default export returns expected output #0
is a bit slim as I have to read the code below to get an idea 
As you added number "#.." you may add TOC on top of the file.
This helps us to understand your intention when reading your code

**Comment by tessus** [comment]
@PackElend I've already asked Sid to do that. But yes, this makes sense. We need proper test names/descriptions.

**Comment by PackElend** [comment]
> No, i still don't understand what you mean by empty single line CSV input

IMHO:

- empty single line csv:
   >    
- csv with empty line:
   >  line1;
    ;
    line3

**Comment by tessus** [comment]
> No, i still don't understand what you mean by empty single line csv input.

I really don't understand how you don't know what an empty line means. Now I understand why you didn't understand the `skipEmptyLines` option.

```
c1,c2,c3
a,b,c

d,e,f


g,h,i
```

**Comment by tessus** [comment]
@coderrsid also, this sentence `Every line of the tests I wrote addresses a certain edge case.` means that you should create a test case for each line, add maybe always a header row `h1,h2,h3` or something and name them according to what they are testing.

**Comment by coderrsid** [comment]
> > No, i still don't understand what you mean by empty single line csv input.
> 
> I really don't understand how you don't know what an empty line means. Now I understand why you didn't understand the `skipEmptyLines` option.
> 
> ```
> c1,c2,c3
> a,b,c
> 
> d,e,f
> 
> 
> g,h,i
> ```
> 

Ohh you meant empty lines in between data, yeah that will be added as an empty row. That is working correctly. Adding a corresponding test though.

**Comment by tessus** [comment]
> Ohh you meant empty lines in between data,

where else would you have empty lines?

**Comment by coderrsid** [comment]
> > Ohh you meant empty lines in between data,
> 
> where else would you have empty lines?

I thought just an empty line inside a csv. My bad.

**Comment by coderrsid** [comment]
> @coderrsid also, this sentence `Every line of the tests I wrote addresses a certain edge case.` means that you should create a test case for each line, add maybe always a header row `h1,h2,h3` or something and name them according to what they are testing.

Sure, i'll do thaat with respect to your comments.

**Comment by tessus** [comment]
> I thought just an empty line inside a csv. My bad.

I'm confused now. My example is an empty line inside a csv.

**Comment by coderrsid** [comment]
> > I thought just an empty line inside a csv. My bad.
> 
> I'm confused now. My example is an empty line inside a csv.

I thought "only" one line which is also empty. But you mean empty lines between a csv data. I  understand that now

**Comment by PackElend** [comment]
> I thought "only" one line which is also empty. But you mean empty lines between a csv data. I understand that now

remember what I told you on discourse, you shall rephrase our question / request. Describe what we said in your own words IN DETAIL.
So we know what you actually understood.

**I'm sorry but that is a have to from now on**
just look above how many comments there are on such a simple thing!

Is that fully understood what I said above?
Describe in your own words what is meant, and what are you going to do!

**Comment by coderrsid** [comment]
> remember what I told you on discourse, you shall rephrase our question / request. Describe what we said in your own words IN DETAIL.
> So we know what you actually understood.

Yeah that's all i did in the conversation.

> **I'm sorry but that is a have to from now on**
> just look above how many comments there are on such a simple thing!

That has been a "have to" from long now stefan.

> Is that fully understood what I said above?
> Describe in your own words what is meant, and what are you going to do!

Yes, that's why i asked again earlier, so that it's fully understood.

**Comment by coderrsid** [comment]
> you tell us. And why.

`\t` means a tab space. So, either what we can do is ignore it and remove it, as a csv editor would not mostly output this in csv file as `\t` but as a tab space like `_____`. But i'd like to consider it and replace it with tab space in string.

**Comment by tessus** [comment]
Why would you want to replace a tab with a string? Dude, seriously. I'm almost giving up. 

First you want to add it to the `delimitersToGuess` and now you are thinking of replacing a tab with a string.

So what are the use cases for each of these 2 options and which one is more probable? I can tell you exactly which one. If you ever used CSV files, then you should know too.

P.S.: There's no such thing as a tab space. `\t` is a tab. It has the length of X spaces depending on settings (8 by default).

**Comment by coderrsid** [comment]
Ok, we can drop this, i just read csv standards '\t' isn't an attribute of csv. 

And Helmut, i don't know how it happens. But i am told to discuss stuff as much as i can and as soon as i do that i just see it creates misunderstandings and looks like you guys are getting pissed answering me idk how.

I'll just add the tests and rename them. Thanks.

**Comment by PackElend** [comment]
> Ok, we can drop this, i just read csv standards '\t' isn't an attribute of csv.

that means you have not done your homework


I strongly advise that you can 3rd person into this here what can advise you what is going wrong here.
It looks like that you have problems understanding the very basic and sorry an empty line is an empty line 

Telling you, again and again, preparing the code that it can be read by a person who does not work on the code on a daily basis is a no-go. 

There should be someone at your university who has software engineering experience. Talk to this person, show him the conversation. This person shall advise you on how to continue.  We cannot hold your hand and show each single step
Keep in mind that the evaluation phase begins soon.

**Comment by tessus** [comment]
No, dropping it will not solve the problem. Ok, let me start from scratch.

You asked, if you should add it to `delimitersToGuess`. I told you that you should tell us and why.
This means that you should do some research on why a TAB for CSVs could have some special meaning. After 5 minutes of searching the net or looking at import dialogs from other applications like LibreOffice or whatnot, you would have probably figured out that a TAB is indeed often used as a separator for CSV files.
Anyone who uses CSVs should know this, especially when they are studying computer science.

But no, you come back with a completely different question whether or not you should replace a TAB with spaces.

I'm really at a loss here. It's like talking to a wall. I also mentioned in the previous PR about the test cases and gave you real ones, yet you only added other pretty useless ones that don't even cover any edge cases that haven't been covererd yet.

Not understanding what an empty line in a data set is, is also very concerning.

The only thing you can really show for yourself is that you took an object and converted it to a markdown table. This entire code could have been written in less than a day. Yet, here we are - 4 weeks later.

I am truly sorry, but I don't think this is working out. Maybe you have to study a few more years to grasp what software engineering and development means. I don't want to be mean, but I always have the distinct impression that you don't know what you are doing.
The reason why I always tried to get you to figure it out yourself was so that you had a learning experience. If I told you everything and how everything was done, it wouldn't be much of a GSoC project - or any project for that matter. I gave you ample hints... many, many times. But you did not understand them or worse ignored them.

The fact is that transforming an object to a markdown table does not warrant 4 weeks of coding time.

**Comment by coderrsid** [comment]
I understand Sir Helmut @tessus . Not understanding me right again. I was trying to focus on the testing part for this weekend before first evaluation. Libreoffice has custom option to use tab as a delimiter, i agree. Now coming back to the question i asked regarding `\t` was editors also output csv containing tab spaces between cell characters as `\t`. So, i tried adding that as a delimiter option in papaparse as you said. Then the results for: 

Example CSV: `a\tb,b\tc,c\td`

So, right now the output is: 
| atb | btc | ctd | 
| --- | --- | --- | 

So, here papa-parse is parsing csv using delimiter '\t' and if we'll add '\t' and `,` to delimitedToGuess, then 
Example:  `a\tb,b\tc,c\td` (containing , and tab space both) results same as earlier

| atb | btc | ctd | 
| --- | --- | --- | 

**So, should we replace that by a space in regex like pipes and backslashes?**

But apart from all that as you're saying about tab seperated values as data, aren't i dealing with CSV (Comma Separated Values) data as table. TSV (Tab Separated Values) as table would be another option, no?

Athough papa parse itself when tested with data containing tab spaces and `,` , parses csv result delimited with tab.
Ex: `a	b,b	c,c	d`

| a | b,b | c,c | d | 
| --- | --- | --- | --- |

**Comment by coderrsid** [comment]
Hey @PackElend, i'm going to create a topic in discourse related to tab separated values and comma separated value and using `\t` for tab spaces too to get insights from the community users and mentors, if needed

**Comment by coderrsid** [comment]
And also more test like empty lines test, empty cell test with data set variation has been added and readable comments for each. Please do review.

**Comment by tessus** [comment]
Why do you want to replace a tab? If a tab is part of the column, the tab should be part of the column in the output as well. Unless there a good reason for not doing so. But you haven't brought up any argument for or against it either.

Additionally, you have to differentiate between 
- TAB as separator
- TAB within a column
- the charcters `\` and `t` (`\t`) that are not a TAB, but just text

But once again, all these test cases are missing. So now I basically gave you the solution for proper testing. At least when it comes to tabs.
But as mentioned before, there are many OTHER edge case you haven't even considered.

> I was trying to focus on the testing part for this weekend before first evaluation.

Hmm, you mentioned in another comment `Yes, i figured out test cases before only`, but that's clearly not the case. You are still writing test cases AFTER.

When looking at the current ones, some of the output is not even valid table markdown syntax. It looks like you make your tests pass your code.

**Comment by coderrsid** [comment]
>Additionally, you have to differentiate between 
>- TAB as separator
>- TAB within a column
>- the charcters `\` and `t` (`\t`) that are not a TAB, but just text
>
>But once again, all these test cases are missing. So now I basically gave you the solution for proper testing. At least when it comes to tabs.
>But as mentioned before, there are many OTHER edge case you haven't even considered.

`\t` is also considered as a tab, you can read it about here (https://stackoverflow.com/questions/15423001/how-are-r-t-and-n-different-from-one-another). Although, these all tests are covered with papa-parse which is the main utility here on different delimiters and spaces between and around text. Do you want me to write them again?

> You are still writing test cases AFTER.
 
I tried to add as much tests i could which would break my csvToMarkdown code. As i already said, i've been testing consistently and couldn't break the code. If you do break the code, please do kindly tell me that unique testcase. I'll add that and other related tests considerably. 

>When looking at the current ones, some of the output is not even valid table markdown syntax.

Can you point me to those cases in code?

**Comment by tessus** [comment]
> `\t` is also considered as a tab

I don't have to read up on it. I've been doing this for 30 years. `\t` is not a TAB, but is interpreted as one in many languages, when the string is enclosed with double quotes. It is taken literally when enclosed in single quotes.

I suggest you read up on it.

Also, you did not understand what I wrote. I specifically said: _the charcters `\` and `t` (`\t`) that are not a TAB, but just text_

If you have a text file (source) that looks like this:

```
h1,h2,h3
c1,c2\th,c3
```

The table will look like this:

```
| h1 | h2 | h3 |
| - | - | - |
| c1 | c2\th | c3 |
```

If not, you did something wrong. You can copy and paste the source into a text file and import it into any application and you will see what I mean.

**Comment by coderrsid** [comment]
Sure. Agreed. Right now, `\t` is pasted as `t` because code is removing backslashes and pipes, so as per i can see, you're suggesting to fix and keep it as `\t` only in table and not change that. Agreed?

**Comment by tessus** [comment]
input = output

however, if there's a pipe and the markdown table uses the pipe symbol to denote a column, the pipe symbol in the column has to be escaped.

I can't be any clearer than that.

**Comment by coderrsid** [comment]
> however, if there's a pipe and the markdown table uses the pipe symbol to denote a column, the pipe symbol in the column has to be escaped.

Yes, the pipes are already being removed from the each cell data as it's used to separate different cells.

**Comment by tessus** [comment]
The pipes are not supposed to be removed from the cell. This is what input = output means. What comes in, comes out.

Let me ask you this:

How can you have a TAB within a column, when you have a TAB separated CSV?
And how do you test it?

The pipe is additionally special, because it is used to build a markdown table.

I'm off to bed.

**Comment by coderrsid** [comment]
> The pipe is additionally special, because it is used to build a markdown table.

Yes, that is what i was trying to say too as `|` is used to create md table. It is escaped in the parsed csv data which is converted into table by adding pipes (basic building block of md table). Wrong choice of words i guess.

**Comment by coderrsid** [comment]
Do i need to test more for delimiters, different characters, and spaces when it is being done here (papa-parse utility): https://github.com/mholt/PapaParse/blob/master/tests/test-cases.js

**Comment by coderrsid** [comment]
Hey @tessus sir, please do review for added tests and also should delimiters test be done again on our client side too other than papa parse? I'm onto creating tests for import csv, pursuing suitable methodologies

**Comment by coderrsid** [comment]
Hey @tessus sir, please do review for added tests for different tokens.

**Comment by tessus** [comment]
I'm sorry, I really don't know what else I can tell you.

You haven't answered my question:

> How can you have a TAB within a column, when you have a TAB separated CSV?
> And how do you test it?
> The pipe is additionally special, because it is used to build a markdown table.

You just don't understand what test cases are. You hardly test any edge cases. 

Additionally some markdown output is incorrect as I have mentioned before. I also don't understand why you remove pipes and backslashes. I said what comes in, should come out.
So, if somebody has a pipe or a backslash in a colum, the table you output is wrong, because data is missing. So why do you remove them?

We have basically told you every single thing you have done so far.

Btw, you have also ignored the [Pull request guidelines](https://joplinapp.org/gsoc2021/pull_request_guidelines/) on more than just one occasion.

I see that you are trying, I really do, but you also have to understand that it's not enough.

It's not my job to teach you test driven development, SW engineering, or any other fundamentals that are a pre-requisite for the project.

Don't get me wrong, if I had the time (which I currently really don't), I'd love doing that, but not for a GSoC project, because it wouldn't be in the spirit of GSoC.

Students are supposed to work mostly in a self-sufficient manner. When they get stuck, mentors can give pointers and help them with getting out of that hole.

But I'm sorry to say, you are constantly stuck.

I don't want to list all of the issues, but here are some that struck me as significant:

The option `skipEmptyLines` would have been worth discussing on he forum. e.g. do people use input that looks this way intentionally?, do they want to be able to have empty lines in the output, ...
But you asked the mentors without doing proper research.
Then we tell you to look into it and to make sure you understand what that option means. But you decided without anything to not skip empty lines. Later it turned out that you thought that an empty line was an empty file.

> I've been testing continuously through the integration.

How? Not with test cases at least.

> Trying to get input from community and you mentors about how should it will break.

This is literally your job. After you have exhausted all options and test cases, then the community can find new ways to break it.

But your test cases are by far not complete - not even close.

What about the following?

```
h1,h2,h3
r1c1,r1c2,r1c3
r2c1;r2c2;r2c3
r2c1|r2c2|r2c3
```

Do you understand what the above test case covers?

Then mixing different separation characters in one line, escaping some, but not others, and so on...

I'm not saying that you have to cover every single possible edge case, because there are way too many, but at least some of the most obvious ones.
But you didn't even get that far. 

For tabs e.g. while `<TAB>` denotes a TAB

```
h1<TAB>h2<TAB>h3
c1<TAB>c2<TAB>c3
a<TAB>b\tn<TAB>c
```

And then you need a bunch of permutations with quoted and escaped separation 
characters and quoted and escaped quoting characters ...

But the above 2 "root" or "base" tests (before the permutations) still do not cover all edge cases. These are just 2 examples (with a lot of permutations).
This last example can be done analogously with all the separation characters with then using separation characters in the columns.

Then there are still a few more I can think of:

Unicode and NULL byte characters...

From a coding perspective this project is not very complex. At least not the way it is currently setup. At one point I mentioned it would make sense to use an abstraction layer, so that it is easily extendable. This would have been slightly more complex, but with OO design still manageable for a project that spans 2 months.

Please, don't be angry with me.

Take this as a way to understand what your shortcomings are and how to improve upon them.

I really hope that you consider to work on some fundamentals, like escaping, quoting, standard test patterns. Because it became clear that you don't understand any of these things.

So, can you honestly tell me that you have worked in a self-sufficient manner and made proper progress? As I mentioned before, the code that is currently available could have been written in a day.

I am sorry, but we cannot continue this as a GSoC project.

**Comment by coderrsid** [comment]
>How can you have a TAB within a column, when you have a TAB separated CSV?
>And how do you test it?
>The pipe is additionally special, because it is used to build a markdown table.

I believe we can escape the tab with \ or add quotes around the space in columns and yes i agree.

>Additionally some markdown output is incorrect as I have mentioned before. I also don't understand why you remove pipes and backslashes. I said what comes in, should come out.
So, if somebody has a pipe or a backslash in a colum, the table you output is wrong, because data is missing. So why do you remove them?
>We have basically told you every single thing you have done so far.

Yes, agreed. I understand the function i have created from csv to markdown is not very efficient and it would make no sense of adding code to it as i think there are tons of cases which we have to refer. So, i'm thinking of going into a direction of using a library which would make it's work easier and more stable and efficient, right?

>Then mixing different separation characters in one line, escaping some, but not others, and so on...
>I'm not saying that you have to cover every single possible edge case, because there are way too many, but at least some of the most obvious ones.
>But you didn't even get that far.
> Don't get me wrong, if I had the time (which I currently really don't), I'd love doing that, but not for a GSoC project, because it wouldn't be in the spirit of GSoC.
>Students are supposed to work mostly in a self-sufficient manner. When they get stuck, mentors can give pointers and help them with getting out of that hole.

I know Helmut, i am not as much as critical thinker as you think respectfully. I just didn't think that on a starting level we can get input like those cases. But i know and understand each bit of what you're saying. I misunderstood the process of discussion with mentors each and everything.

> And then you need a bunch of permutations with quoted and escaped separation
characters and quoted and escaped quoting characters ...
>But the above 2 "root" or "base" tests (before the permutations) still do not cover all edge cases. These are just 2 examples (with a lot of permutations).
>This last example can be done analogously with all the separation characters with then using separation characters in the columns.

Sure, i'll test them all and come back with better unit test cases and code.

>Please, don't be angry with me.
>Take this as a way to understand what your shortcomings are and how to improve upon them.

I'd never be angry of you Helmut. I admire your thought process and learning to develop towards it. 

>I really hope that you consider to work on some fundamentals, like escaping, quoting, standard test patterns. Because it became clear that you don't understand any of these things.
>So, can you honestly tell me that you have worked in a self-sufficient manner and made proper progress? As I mentioned before, the code that is currently available could have been written in a day.

I understand at the start i had some few bumps related to understanding the flow. But, yes i tried researching everytime before i cam to any conclusion. Yes, i have tried to work in self-sufficient manner by giving it all the time needed even more than my university exams (which btw got over today). But please let me take one more chance of proving me and let me come back with a better and complete pull request with all the changes as you want and needed.

**Comment by laurent22** [comment]
Our dilemma is that we already saw the type of work you produce when we aren't helping, and we have no reasons to think if we stop helping things will get better.

Also we need to assess the quality of your work, but this is difficult because you got so much help from the six of us, that's it's almost not your work anymore but ours. It's supposed to be your project. You have to make the important decisions like what lib to use, and how, think about the project architecture, and unfortunately you didn't do that part. I remember I really had to insist again and again to get you to use a proper csv parsing lib.

Also as Tessus mentioned while the plugin works there's not a lot of original code in there - just a call to parse the CSV, then a routine to convert this to Markdown, and a few tests.

So I'm afraid I'm not convinced either that this project will get somewhere if you're left on your own. And it doesn't make sense either for us to spend so much time helping you because it's supposed to be your project.

**Comment by coderrsid** [comment]
Hey @laurent22 , i agree to all your insights. Though firstly according to the proposal, i described the implementation of this project contains steps like `Designing the Paste Special plugin component,  Implementing the design of Paste Special plugin component, Deploying it to the Desktop Client, including different sets of testing on the component` which is 70% of the project and has been completed before the first evaluation according to the decided schedule even though you personally you know how unfortunate the time was for me in that starting two weeks straight, i was fixing the forked copy on my mac machine with the help of thanks to you especially and other mentors for which insight was obviously needed. As joplin is a great and big opensource project, and the issue i faced was regarding packages and code of ios lib in joplin, which i was not very familiar with in the span of my contribution to project over 2 years as i'm familiar to desktop version and have contributed to that, so help was indeed required. But i overcame that problem too.

Secondly, my proposal got agreed over the package papa-parse and csv to markdown table conversion code/package for which you suggested that i should use papa-parse for csv results as they are the best in class for parsing, so i turned to that path, and wrote my own stable code for the conversion to markdown table (not copied from anywhere) as i'm not gonna deny mentors, just gonna be intrigued and ask for permissions and queries always regarding the usage. Guidance is always what i have seeked, for the parts i couldn't get out of (i.e. loop holes) and opinions for how can we break the code. As @tessus said, there are more test cases which could be added and gave a very bright insight that i have to choose wisely that at what points the code will break (i.e. `bunch of permutations with quoted and escaped separation characters and quoted and escaped quoting characters, Unicode and NULL byte characters`). So, i've been testing all those parts and also created bigger and complex test cases which i'm gonna push right away for review.

Overall, laurent and helmut, i'm also one of the longest connected person working on GSoC for Joplin that is over 2 years. Believe me, the only thing i learnt in the community is that the feature doesn't work if not tested properly and created in the best object oriented usage. You can already see that users are loving the plugin and giving positive reviews (https://discourse.joplinapp.org/t/week-4-first-version-is-out-paste-special-plugin/18507). I believe this is a big community and thousand of users are gonna test and use. I've also already achieved importing csv as table which i'm gonna make a pull request for too with test cases. It was just the beginning part and debugging parts, i asked major help for. For the testing part, i had the idea that basic coverage is done and version was released out, so that if some major complex unique dataset is used by any user and it fails, we can obviously change the all the simplest parts of code and i've made the project in the most modular way and can also add testing related to it. I seek guidance because i don't want people to suffer because of poor performance and design and implementation of plugin and after al the google group of student GSoC community always told that when in doubt, ask mentors, solve issues collectively and apply the best possible solution for project so that the plugin does not go to waste due to poor overlook, which i always asked for. Thanks laurent and helmut and i admire your reviews and would definitely give my better and best to this project ahead. Please trust me, i'm really looking forward to work with all the hard work and energy. Regards.

**Comment by tessus** [comment]
Sid, I told you all the relevant test cases in my previous comment. Once again, the solution came from us.

This is not how GSoC works. The fact that people like the plugin doesn't change the fact that this project cannot be run under the mantle of GSoC anymore. 

I also stated that you broke the PR guidelines, but you have mentioned us yet again. You are the ONLY one who does that. Also, not to mention the force-push and not disclosing borrowed code earlier. Not really important anymore, but what's up with that?

Laurent also brought it to the point. We basically would have to evaluate ourselves for helping you that much, instead of evaluating your work. Because in reality there is nothing you did on your own. Nothing. So we can't evaluate your work. We even told you to use the returned object from PapaParse and transform it into a table.
Then you remove characters from the input in he ouput without explanation or reason. And you can't come up with proper test cases on your own. All of sudden the test case for empty lines is gone too. 

And, btw, a table like this is not valid markdown (another thing you didn't figure out, even though I mentioned there is something wrong):

```
| a | b | c | d |
|---|---|---|---|
| |
| e | f | g | h |
```

But instead of fixing invalid output, you apparently removed the test.

Either way. I cannot evaluate work that hasn't been done. There is no way continuing this for GSoC.

**Comment by coderrsid** [comment]
Helmut, it's literally not like that. Respectfully, we have just been discussing these testcases because we need a wider thought of different datasets that can be tested, if you are counting the help from the issues that arrived at the start after pulling latest code from dev branch of joplin. Please do consider, that was a base code error about android.

> I also stated that you broke the PR guidelines, but you have mentioned us yet again. You are the ONLY one who does that. Also, not to mention the force-push and not disclosing borrowed code earlier.

I mentioned laurent so that he could also understand that this reply also contains reply to his comment respectively and yours, overall. There was a single force push, removing a single commit and i apologised earlier for that and now i do too. 

> Laurent also brought it to the point. We basically would have to evaluate ourselves for helping you that much, instead of evaluating your work. Because in reality there is nothing you did on your own. Nothing. So we can't evaluate your work. We even told you to use the returned object from PapaParse and transform it into a table.
Then you remove characters from the input in he output without explanation or reason. And you can't come up with proper test cases on your own.

Please sir, should i not ask for insights? That's all i needed. But to convey my thought process, and you to convey yours respectively took some time and still we're not behind schedule and has release plugin on stable basis.

>  All of sudden the test case for empty lines is gone too.

It's not gone sir. If you check just below that a new case has been added which tests empty line overall and multiple empty cells column too.

> And, btw, a table like this is not valid markdown (another thing you didn't figure out, even though I mentioned there is something wrong):

>>| a | b | c | d |
>>|---|---|---|---|
>>| |
>>| e | f | g | h |

This'd be fixed as soon as i apply md table prettifier to this, which i mentioned earlier that i will. But, actually this PR is not related to that, so i didn't add prettifier.

> But instead of fixing invalid output, you apparently removed the test.

Sir, I just created a new test instead of it just below that, to check if [null cells](https://docs.snowflake.com/en/user-guide/data-unload-considerations.html#empty-strings-and-null-values) are combining to add up empty row in table.

> Either way. I cannot evaluate work that hasn't been done. There is no way continuing this for GSoC.

I request you Helmut, please don't look it that way. I have done quite research and have just not been able to convey my thoughts properly as this is my first open source community project under mentors. I have given all my time to this even more than my last semester university examinations and thanks to you that your insights always made this project more powerful. I request you that i really want to purse this project Helmut under GSoC

**Comment by coderrsid** [comment]
I've also been working by side on creating the first version of pasting Webpage as Markdown using Turndown

[Paste HTML as Markdown](https://gifyu.com/image/B82H)

**Comment by tessus** [comment]
You don't understand what I am saying. I cannot evaluate your work, because you haven't done any work yourself.

There is no other way to see the facts.

**Comment by coderrsid** [comment]
> You don't understand what I am saying. I cannot evaluate your work, because you haven't done any work yourself.
> 
> There is no other way to see the facts.

Please understand that this is a very small project nothing complex. The main code for conversion of csv ro markdown is written by me myself here which is one of the 2 big fishes inside this project helmut. I kindly request to please stop and process our hardwork and give a last chance.

**Comment by PackElend** [comment]
> The main code for conversion of csv ro markdown is written by me myself

but please reflect on what was done solely by yourself and which part was done according to answers from Laurent and tessues

**Comment by coderrsid** [comment]
> > The main code for conversion of csv ro markdown is written by me myself
> 
> but please reflect on what was done solely by yourself and which part was done according to answers from Laurent and tessues

Sure stefan. Starting from the very start of proposal, i proposed to use papa-parse for validation and a library named csv-to-markdown table from conversion to a md table. So after i achieved this workflow, laurent suggested a small change that the results from papa parse can be used to create a markdown table and should make more sense. So, then i went ahead analysed all results of papa-parse and wrote the code for conversion of csv parsed results to markdown table myself and not copied/used that from anywhere. For the tests, i wrote the prominent 15 tests that covered validation of csv format and multiple type of inputs containing numbers and text and boundary cases so then we released it for the community. After that, Helmut gave me a great insight about how csv could be more complex and should be tested in more ways and those hints and brainstorming has suggested me to write even more critical tests and i came up with 15 more testcases, some from hints and others from my sole research. This was all regarding what happened for the project. 

But all mentors helped me only when i was facing failure of joplin production software on my mac machine due to some `podError` which even then couldn't be solved but absolutely i took a way around of it and motivated myself that i should not give up here and work ahead. Stefan, respectfully we've been guided by student gsoc community members to always ask and communicate, if ever in doubt, so that we do not move away from the path the organisation wants and that's all i seek from the very start.

**Comment by coderrsid** [comment]
Also stefan, if my thought process is not right here for communicating about a larger number of details here and if i should change or modify some ways here, so i'm absolutely looking forward to working in a way that i solve almost all problems by my sole work and own the plugin in a 100% manner. I can surely walk that way as what i faced at the starting of the timeline, i can absolutely assure you it's not gonna happen again and absolutely i'm willing to modify the way of process if needed by my sole hard work. Thanks to all mentors.

**Pull request closed without merging**
